### ISSUE TITLE
Tienes instrucciones de instalación

### ISSUE THREAD

**Issue by johnfelipe** [jlgasparrini/sistema-legislativo-digital#12]

**Comment by jlgasparrini** [comment]
Hola! Disculpa, pero el sistema esta recién empezado, en un par de meses estará listo y colocaremos instrucciones de instalación :+1: 
¿Para que lo necesitas?

**Comment by johnfelipe** [comment]
Quisiera tener un demo para colombia, suena interesante el tuyo

**Comment by jlgasparrini** [comment]
En unos meses estate atento que subiremos el demo :+1:

**Comment by johnfelipe** [comment]
Tu opinas que haya una release en cuantos meses?

**Comment by rodrigoabella** [comment]
Calculamos que para noviembre o diciembre ya va a estar disponible.

**Comment by johnfelipe** [comment]
Ya estamos en noviembre, falta poco?

**Comment by rodrigoabella** [comment]
A fines de diciembre va a haber un release con las funcionalidades más importantes!!

**Comment by johnfelipe** [comment]
Hola amigo como va la realese?

**Comment by johnfelipe** [comment]
Hola amigo, como vamos?

**Comment by johnfelipe** [comment]
Hola alguna novedad?
